// Estados de la Hoja de Estados oficial de Tainted Grail: Reyes de la Perdición.
// Fuente: ES_KoR_TG_Status_Sheet_210x297.pdf de awakenrealms.com.
// `max` es el número de casillas. Por defecto las casillas llevan número 1..max;
// `unnumbered: true` marca los estados cuyas casillas en la hoja oficial están
// vacías (sin número impreso).

export const STATUSES = [
  { id: 'abandonado',                     name: 'Abandonado',                        max: 2  },
  { id: 'abastecimiento',                 name: 'Abastecimiento',                    max: 9  },
  { id: 'actuaciones',                    name: 'Actuaciones',                       max: 4  },
  { id: 'alianza_del_pardobosque',        name: 'Alianza del Pardobosque',           max: 4  },
  { id: 'amigo_de_la_nobleza',            name: 'Amigo de la nobleza',               max: 5  },
  { id: 'ascuas',                         name: 'Ascuas',                            max: 6  },
  { id: 'burocracia',                     name: 'Burocracia',                        max: 5  },
  { id: 'buscador',                       name: 'Buscador',                          max: 9  },
  { id: 'calles_de_sorlois',              name: 'Calles de Sorlois',                 max: 4, unnumbered: true },
  { id: 'caminos_alternativos',           name: 'Caminos alternativos',              max: 12 },
  { id: 'campeon_de_los_campesinos',      name: 'Campeón de los campesinos',         max: 7  },
  { id: 'canciones_de_avalon',            name: 'Canciones de Ávalon',               max: 3  },
  { id: 'cartografiando_el_pantano',      name: 'Cartografiando el pantano',         max: 4, unnumbered: true },
  { id: 'claves_y_contrasenas',           name: 'Claves y contraseñas',              max: 2  },
  { id: 'cola_de_la_suerte',              name: 'Cola de la suerte',                 max: 5  },
  { id: 'companeros',                     name: 'Compañeros',                        max: 4  },
  { id: 'compensacion',                   name: 'Compensación',                      max: 4, unnumbered: true },
  { id: 'constructores_de_sorlois',       name: 'Constructores de Sorlois',          max: 4  },
  { id: 'corazon_frio',                   name: 'Corazón frío',                      max: 10 },
  { id: 'cosecha_de_la_rareza',           name: 'Cosecha de la Rareza',              max: 8  },
  { id: 'curiosidades',                   name: 'Curiosidades',                      max: 10 },
  { id: 'derretido',                      name: 'Derretido',                         max: 4, unnumbered: true },
  { id: 'deuda',                          name: 'Deuda',                             max: 4, unnumbered: true },
  { id: 'documentos_antiguos',            name: 'Documentos antiguos',               max: 5  },
  { id: 'encuentros_fortuitos',           name: 'Encuentros fortuitos',              max: 9  },
  { id: 'enfrentarse_a_la_perdicion',     name: 'Enfrentarse a la Perdición',        max: 4  },
  { id: 'epilogos',                       name: 'Epílogos',                          max: 3  },
  { id: 'final_del_camino',               name: 'Final del camino',                  max: 8  },
  { id: 'forrajeo',                       name: 'Forrajeo',                          max: 11 },
  { id: 'fracasos_del_anticaballero',     name: 'Fracasos del Anticaballero',        max: 4  },
  { id: 'funeral_real',                   name: 'Funeral real',                      max: 5  },
  { id: 'futuro_de_avalon',               name: 'Futuro de Ávalon',                  max: 11 },
  { id: 'giro_del_destino',               name: 'Giro del destino',                  max: 4  },
  { id: 'hazanas_destacadas',             name: 'Hazañas destacadas',                max: 8  },
  { id: 'historias_de_hoguera',           name: 'Historias de hoguera',              max: 4, unnumbered: true },
  { id: 'informante',                     name: 'Informante',                        max: 6  },
  { id: 'insolente',                      name: 'Insolente',                         max: 5  },
  { id: 'isolut',                         name: 'Isolut',                            max: 7  },
  { id: 'jolgorio',                       name: 'Jolgorio',                          max: 2  },
  { id: 'kendrick',                       name: 'Kendrick',                          max: 7  },
  { id: 'lecciones_de_astucia',           name: 'Lecciones de astucia',              max: 4, unnumbered: true },
  { id: 'lecciones_de_inspiracion',       name: 'Lecciones de inspiración',          max: 4, unnumbered: true },
  { id: 'lecciones_extranas',             name: 'Lecciones extrañas',                max: 9  },
  { id: 'lecciones_pasadas',              name: 'Lecciones pasadas',                 max: 4  },
  { id: 'leve_impresion',                 name: 'Leve impresión',                    max: 9  },
  { id: 'libertad',                       name: 'Libertad',                          max: 8  },
  { id: 'mangante',                       name: 'Mangante',                          max: 9  },
  { id: 'mensajes_secretos',              name: 'Mensajes secretos',                 max: 3  },
  { id: 'mercancia_limitada',             name: 'Mercancía limitada',                max: 4, unnumbered: true },
  { id: 'negociador',                     name: 'Negociador',                        max: 9  },
  { id: 'obstaculos',                     name: 'Obstáculos',                        max: 4  },
  { id: 'pecados_del_obispo',             name: 'Pecados del Obispo',                max: 5  },
  { id: 'pequeno_favor',                  name: 'Pequeño favor',                     max: 10 },
  { id: 'pistas',                         name: 'Pistas',                            max: 2  },
  { id: 'planes_y_tramas',                name: 'Planes y tramas',                   max: 9  },
  { id: 'productos_extranjeros',          name: 'Productos extranjeros',             max: 4, unnumbered: true },
  { id: 'rastreador',                     name: 'Rastreador',                        max: 4  },
  { id: 'realista',                       name: 'Realista',                          max: 4  },
  { id: 'reconstruyendo_lothian',         name: 'Reconstruyendo Lothian',            max: 8  },
  { id: 'represion',                      name: 'Represión',                         max: 6  },
  { id: 'revelaciones_del_rarovidrio',    name: 'Revelaciones del rarovidrio',       max: 11 },
  { id: 'rumores_y_habladurias',          name: 'Rumores y habladurías',             max: 7  },
  { id: 'secretos_de_familia',            name: 'Secretos de familia',               max: 10 },
  { id: 'secretos_de_la_reina_del_ambar', name: 'Secretos de la Reina del Ámbar',    max: 4  },
  { id: 'sendero_venediano',              name: 'Sendero venediano',                 max: 10 },
  { id: 'sequia',                         name: 'Sequía',                            max: 8  },
  { id: 'temas_personales',               name: 'Temas personales',                  max: 15 },
  { id: 'temerario',                      name: 'Temerario',                         max: 7  },
  { id: 'terrores_y_peligros',            name: 'Terrores y peligros',               max: 10 },
  { id: 'tierra_prohibida',               name: 'Tierra prohibida',                  max: 8  },
  { id: 'topografia',                     name: 'Topografía',                        max: 10 },
  { id: 'ventaja_agua',                   name: 'Ventaja: agua',                     max: 4, unnumbered: true },
  { id: 'ventaja_rareza',                 name: 'Ventaja: Rareza',                   max: 4, unnumbered: true },
  { id: 'verdad_amarga',                  name: 'Verdad amarga',                     max: 5  },
  { id: 'viajeros_anteriores',            name: 'Viajeros anteriores',               max: 4  },
];

export const stripAccents = (s) =>
  s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
